#index:
#    path: /
#    controller: App\Controller\DefaultController::index
site_home:
  path: /
  controller: App\Controller\IndexController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
registration:
  path: /register
  controller: App\Controller\RegistrationController::register
